
USE Restaurante;

INSERT INTO Menu(nombre) VALUES('GASEOSAS');
INSERT INTO Menu(nombre) VALUES('BEBIDAS ALCOHÓLICAS');
INSERT INTO Menu(nombre) VALUES('BOTANAS');
INSERT INTO Menu(nombre) VALUES('DESAYUNOS');
INSERT INTO Menu(nombre) VALUES('ALMUERZOS');
INSERT INTO Menu(nombre) VALUES('CENAS');
INSERT INTO Menu(nombre) VALUES('BEBIDAS CALIENTES');
INSERT INTO Menu(nombre) VALUES('REFACCIONES');
